services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dunning
      POSTGRES_PASSWORD: dunning123
      POSTGRES_DB: dunning_engine
    ports:
      - "5432:5432"
    volumes:
      - dunning_pgdata:/var/lib/postgresql/data

volumes:
  dunning_pgdata: